In [5]:
import copy, numpy as np
np.random.seed(0)

In [55]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    
    # how much did we miss?
    l1_error = y - l1
    if iter%100==0: print(f"{iter}\n{l1_error}")

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print("Output After Training:")
print(l1)

0
[[-0.2689864 ]
 [-0.36375058]
 [ 0.76237183]
 [ 0.6737243 ]]
100
[[-0.10975431]
 [-0.0914018 ]
 [ 0.07391609]
 [ 0.08910196]]
200
[[-0.07532702]
 [-0.06151182]
 [ 0.04977973]
 [ 0.06113161]]
300
[[-0.06044451]
 [-0.04912604]
 [ 0.03979486]
 [ 0.04907442]]
400
[[-0.05175173]
 [-0.04198947]
 [ 0.03403931]
 [ 0.0420343 ]]
500
[[-0.04590957]
 [-0.03722323]
 [ 0.03019293]
 [ 0.03730225]]
600
[[-0.0416479 ]
 [-0.03375824]
 [ 0.02739494]
 [ 0.03384954]]
700
[[-0.03836706]
 [-0.03109611]
 [ 0.02524409]
 [ 0.03119075]]
800
[[-0.03574306]
 [-0.02896968]
 [ 0.02352521]
 [ 0.02906372]]
900
[[-0.03358382]
 [-0.02722134]
 [ 0.02211135]
 [ 0.02731301]]
1000
[[-0.03176745]
 [-0.02575143]
 [ 0.02092221]
 [ 0.02583995]]
1100
[[-0.03021241]
 [-0.02449348]
 [ 0.01990419]
 [ 0.02457858]]
1200
[[-0.02886188]
 [-0.02340124]
 [ 0.01902   ]
 [ 0.02348288]]
1300
[[-0.0276749 ]
 [-0.02244142]
 [ 0.01824281]
 [ 0.0225197 ]]
1400
[[-0.02662111]
 [-0.02158939]
 [ 0.01755272]
 [ 0.02166446]]
1500
[[-0.02567747]
 [

In [82]:
import numpy as np

def nonlin(x,deriv=False):
	if(deriv==True):
	    return x*(1-x)

	return 1/(1+np.exp(-x))
    
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],[1],[1],[0]])

np.random.seed(1)

# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

for j in range(6000):

	# Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1)) #predicted values

    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j% 600) == 0:
        print("Error:" + str(np.mean(np.abs(l2_error))))
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error*nonlin(l2,deriv=True)

    # how much did each l1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1,deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)


Error:0.4964100319027255
Error:0.0763573184071118
Error:0.03635576307488306
Error:0.02610839193835602
Error:0.02114168488173238
Error:0.018121400645678867
Error:0.01605414546245479
Error:0.014532233896512021
Error:0.013355002128910096
Error:0.012411228842136872
